-- Crear extension
CREATE EXTENSION dblink;

-- Eliminación tablas
DROP TABLE IF EXISTS ESTUDIANTE;
DROP TABLE IF EXISTS PROYECTO;
DROP TABLE IF EXISTS SERVIDOR;

-- Creación tablas
CREATE TABLE SERVIDOR(
    SERV_ID VARCHAR(3) PRIMARY KEY,
    HOST VARCHAR(30) NOT NULL UNIQUE,
    PUERTO NUMERIC(4, 0) NOT NULL,
    USUARIO VARCHAR(30) NOT NULL,
    CONTRASENA VARCHAR(30) NOT NULL
);

CREATE TABLE PROYECTO(
    ID_PROY CHAR(2) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    SERV_ID VARCHAR(3) NOT NULL
);

ALTER TABLE PROYECTO ADD CONSTRAINT FK_PROYECTO_SERVIDOR FOREIGN KEY(SERV_ID) REFERENCES SERVIDOR(SERV_ID);

CREATE TABLE ESTUDIANTE(
    ID_EST SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    ID_PROY CHAR(2) NOT NULL
);

-- Definición constraints
ALTER TABLE ESTUDIANTE ADD CONSTRAINT FK_ESTUDIANTE_PROYECTO FOREIGN KEY(ID_PROY) REFERENCES PROYECTO(ID_PROY);