version: '3.9'

services:
  global:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: global
    volumes:
      - data_global:/var/lib/postgresql/data
      - './a-creation.sql:/docker-entrypoint-initdb.d/1.sql:ro'

  sistemas:
    image: postgres:15-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: sistemas
    volumes:
      - data_sistemas:/var/lib/postgresql/data
      - './a-creation.sql:/docker-entrypoint-initdb.d/1.sql:ro'
      - './sistemas:/docker-entrypoint-initdb.d/2.sql:ro'
  
  catastral:
    image: postgres:15-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: catastral
    volumes:
      - data_catastral:/var/lib/postgresql/data
      - './a-creation.sql:/docker-entrypoint-initdb.d/1.sql:ro'
      - './catastral/:/docker-entrypoint-initdb.d/2.sql:ro'

  electronica:
    image: postgres:15-alpine
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: electronica
    volumes:
      - data_electronica:/var/lib/postgresql/data
      - './a-creation.sql:/docker-entrypoint-initdb.d/1.sql:ro'
      - './ingenieria:/docker-entrypoint-initdb.d/2.sql:ro'

volumes:
  data_global:
  data_sistemas:
  data_catastral:
  data_electronica:
