-- Crear extension
CREATE EXTENSION dblink;

-- Eliminación tablas
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS PROYECTO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS SERVIDOR;

-- Creación tablas
CREATE TABLE SERVIDOR(
    CIUDAD VARCHAR(3) PRIMARY KEY,
    HOST VARCHAR(30) NOT NULL UNIQUE,
    PUERTO NUMERIC(4, 0) NOT NULL,
    USUARIO VARCHAR(30) NOT NULL,
    CONTRASENA VARCHAR(30) NOT NULL
);

CREATE TABLE DEPARTAMENTO(
    ID_DEP CHAR(2) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    CIUDAD VARCHAR(3) NOT NULL
);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_SERVIDOR FOREIGN KEY(CIUDAD) REFERENCES SERVIDOR(CIUDAD);

CREATE TABLE EMPLEADO(
    ID_EMP SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    SALARIO NUMERIC(10, 0) NOT NULL,
    ID_DEP CHAR(2) NOT NULL
);

-- Definición constraints
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO_DEPARTAMENTO FOREIGN KEY(ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP);

create TABLE PROYECTO(
    ID_PROY CHAR(2) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    PRESUPUESTO NUMERIC(20,0) NOT NULL,
    ID_DEP CHAR(2) NOT NULL
);

ALTER TABLE PROYECTO ADD CONSTRAINT FK_EMPLEADO_DEPARTAMENTO FOREIGN KEY(ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP);